---

- name: add puppet repository in xenial
  apt:
   deb: https://apt.puppetlabs.com/puppet5-release-xenial.deb
   state: present
  when:
   - ansible_os_family == "Debian"
   - ansible_distribution_release == "xenial"

- name: Add puppet repository
  yum:
   name: https://yum.puppet.com/puppet5/puppet5-release-el-6.noarch.rpm
   state: present
  when:
   - ansible_os_family == "RedHat"
   - ansible_distribution_major_version == "7"
