- name: start o apache em redhat
  service:
   name: httpd
   state: started
  when: ansible_os_family == "RedHat"

- name: start o apache em debian
  service:
   name: apache2
   state: started
  when: ansible_os_family == "Debian"

