---

- name: minha primeira playbook
  hosts: devops docker
  tasks: 
   - name: criando usuario
     user: 
      name: devops
      state: present
      password: '$1$Rlq0h0Ps$JXChLCpqHgRVlb159LTyI.'

   - name: instalando pacote na playbook
     package:
      name: vim  

   - name: copiando um arquivo
     copy:
      src: config.php
      dest: /tmp/
